// Core Pathfinder spell-grant tables. Spell names and level mappings only.
// Sources: https://legacy.aonprd.com/coreRuleBook/classes/cleric.html
//          https://legacy.aonprd.com/coreRuleBook/classes/sorcerer.html
import type { DomainDefinition } from "./domains";
import type { SpellBloodlineDefinition } from "./bloodlines";
export const CORE_DOMAIN_SPELLS: DomainDefinition[] = [
  {
    id: "air",
    name: "Air",
    className: "cleric",
    spells: {
      "1": "Obscuring Mist",
      "2": "Wind Wall",
      "3": "Gaseous Form",
      "4": "Air Walk",
      "5": "Control Winds",
      "6": "Chain Lightning",
      "7": "Elemental Body IV",
      "8": "Whirlwind",
      "9": "Elemental Swarm",
    },
    spellNotes: {
      "7": "air only",
      "9": "air spell only",
    },
  },
  {
    id: "animal",
    name: "Animal",
    className: "cleric",
    spells: {
      "1": "Calm Animals",
      "2": "Hold Animal",
      "3": "Dominate Animal",
      "4": "Summon Nature's Ally 4",
      "5": "Beast Shape III",
      "6": "Antilife Shell",
      "7": "Animal Shapes",
      "8": "Summon Nature's Ally 8",
      "9": "Shapechange",
    },
    spellNotes: {
      "4": "animals only",
      "5": "animals only",
      "8": "animals only",
    },
  },
  {
    id: "artifice",
    name: "Artifice",
    className: "cleric",
    spells: {
      "1": "Animate Rope",
      "2": "Wood Shape",
      "3": "Stone Shape",
      "4": "Minor Creation",
      "5": "Fabricate",
      "6": "Major Creation",
      "7": "Wall of Iron",
      "8": "Statue",
      "9": "Prismatic Sphere",
    },
  },
  {
    id: "chaos",
    name: "Chaos",
    className: "cleric",
    spells: {
      "1": "Protection from Law",
      "2": "Align Weapon",
      "3": "Magic Circle against Law",
      "4": "Chaos Hammer",
      "5": "Dispel Law",
      "6": "Animate Objects",
      "7": "Word of Chaos",
      "8": "Cloak of Chaos",
      "9": "Summon Monster 9",
    },
    spellNotes: {
      "2": "chaos only",
      "9": "chaos spell only",
    },
  },
  {
    id: "charm",
    name: "Charm",
    className: "cleric",
    spells: {
      "1": "Charm Person",
      "2": "Calm Emotions",
      "3": "Suggestion",
      "4": "Heroism",
      "5": "Charm Monster",
      "6": "Geas/Quest",
      "7": "Insanity",
      "8": "Demand",
      "9": "Dominate Monster",
    },
  },
  {
    id: "community",
    name: "Community",
    className: "cleric",
    spells: {
      "1": "Bless",
      "2": "Shield Other",
      "3": "Prayer",
      "4": "Imbue with Spell Ability",
      "5": "Telepathic Bond",
      "6": "Heroes' Feast",
      "7": "Refuge",
      "8": "Cure Critical Wounds, Mass",
      "9": "Miracle",
    },
  },
  {
    id: "darkness",
    name: "Darkness",
    className: "cleric",
    spells: {
      "1": "Obscuring Mist",
      "2": "Blindness/Deafness",
      "3": "Deeper Darkness",
      "4": "Shadow Conjuration",
      "5": "Summon Monster 5",
      "6": "Shadow Walk",
      "7": "Power Word Blind",
      "8": "Shadow Evocation, Greater",
      "9": "Shades",
    },
    spellNotes: {
      "2": "only to cause blindness",
      "5": "summons 1d3 shadows",
    },
  },
  {
    id: "death",
    name: "Death",
    className: "cleric",
    spells: {
      "1": "Cause Fear",
      "2": "Death Knell",
      "3": "Animate Dead",
      "4": "Death Ward",
      "5": "Slay Living",
      "6": "Create Undead",
      "7": "Destruction",
      "8": "Create Greater Undead",
      "9": "Wail of the Banshee",
    },
  },
  {
    id: "destruction",
    name: "Destruction",
    className: "cleric",
    spells: {
      "1": "True Strike",
      "2": "Shatter",
      "3": "Rage",
      "4": "Inflict Critical Wounds",
      "5": "Shout",
      "6": "Harm",
      "7": "Disintegrate",
      "8": "Earthquake",
      "9": "Implosion",
    },
  },
  {
    id: "earth",
    name: "Earth",
    className: "cleric",
    spells: {
      "1": "Magic Stone",
      "2": "Soften Earth and Stone",
      "3": "Stone Shape",
      "4": "Spike Stones",
      "5": "Wall of Stone",
      "6": "Stoneskin",
      "7": "Elemental Body IV",
      "8": "Earthquake",
      "9": "Elemental Swarm",
    },
    spellNotes: {
      "7": "earth only",
      "9": "earth spell only",
    },
  },
  {
    id: "evil",
    name: "Evil",
    className: "cleric",
    spells: {
      "1": "Protection from Good",
      "2": "Align Weapon",
      "3": "Magic Circle against Good",
      "4": "Unholy Blight",
      "5": "Dispel Good",
      "6": "Create Undead",
      "7": "Blasphemy",
      "8": "Unholy Aura",
      "9": "Summon Monster 9",
    },
    spellNotes: {
      "2": "evil only",
      "9": "evil spell only",
    },
  },
  {
    id: "fire",
    name: "Fire",
    className: "cleric",
    spells: {
      "1": "Burning Hands",
      "2": "Produce Flame",
      "3": "Fireball",
      "4": "Wall of Fire",
      "5": "Fire Shield",
      "6": "Fire Seeds",
      "7": "Elemental Body IV",
      "8": "Incendiary Cloud",
      "9": "Elemental Swarm",
    },
    spellNotes: {
      "7": "fire only",
      "9": "fire spell only",
    },
  },
  {
    id: "glory",
    name: "Glory",
    className: "cleric",
    spells: {
      "1": "Shield of Faith",
      "2": "Bless Weapon",
      "3": "Searing Light",
      "4": "Holy Smite",
      "5": "Righteous Might",
      "6": "Undeath to Death",
      "7": "Holy Sword",
      "8": "Holy Aura",
      "9": "Gate",
    },
  },
  {
    id: "good",
    name: "Good",
    className: "cleric",
    spells: {
      "1": "Protection from Evil",
      "2": "Align Weapon",
      "3": "Magic Circle against Evil",
      "4": "Holy Smite",
      "5": "Dispel Evil",
      "6": "Blade Barrier",
      "7": "Holy Word",
      "8": "Holy Aura",
      "9": "Summon Monster 9",
    },
    spellNotes: {
      "2": "good only",
      "9": "good spell only",
    },
  },
  {
    id: "healing",
    name: "Healing",
    className: "cleric",
    spells: {
      "1": "Cure Light Wounds",
      "2": "Cure Moderate Wounds",
      "3": "Cure Serious Wounds",
      "4": "Cure Critical Wounds",
      "5": "Breath of Life",
      "6": "Heal",
      "7": "Regenerate",
      "8": "Cure Critical Wounds, Mass",
      "9": "Heal, Mass",
    },
  },
  {
    id: "knowledge",
    name: "Knowledge",
    className: "cleric",
    spells: {
      "1": "Comprehend Languages",
      "2": "Detect Thoughts",
      "3": "Speak with Dead",
      "4": "Divination",
      "5": "True Seeing",
      "6": "Find the Path",
      "7": "Legend Lore",
      "8": "Discern Location",
      "9": "Foresight",
    },
  },
  {
    id: "law",
    name: "Law",
    className: "cleric",
    spells: {
      "1": "Protection from Chaos",
      "2": "Align Weapon",
      "3": "Magic Circle against Chaos",
      "4": "Order's Wrath",
      "5": "Dispel Chaos",
      "6": "Hold Monster",
      "7": "Dictum",
      "8": "Shield of Law",
      "9": "Summon Monster 9",
    },
    spellNotes: {
      "2": "law only",
      "9": "law spell only",
    },
  },
  {
    id: "liberation",
    name: "Liberation",
    className: "cleric",
    spells: {
      "1": "Remove Fear",
      "2": "Remove Paralysis",
      "3": "Remove Curse",
      "4": "Freedom of Movement",
      "5": "Break Enchantment",
      "6": "Dispel Magic, Greater",
      "7": "Refuge",
      "8": "Mind Blank",
      "9": "Freedom",
    },
  },
  {
    id: "luck",
    name: "Luck",
    className: "cleric",
    spells: {
      "1": "True Strike",
      "2": "Aid",
      "3": "Protection from Energy",
      "4": "Freedom of Movement",
      "5": "Break Enchantment",
      "6": "Mislead",
      "7": "Spell Turning",
      "8": "Moment of Prescience",
      "9": "Miracle",
    },
  },
  {
    id: "madness",
    name: "Madness",
    className: "cleric",
    spells: {
      "1": "Confusion, Lesser",
      "2": "Touch of Idiocy",
      "3": "Rage",
      "4": "Confusion",
      "5": "Nightmare",
      "6": "Phantasmal Killer",
      "7": "Insanity",
      "8": "Scintillating Pattern",
      "9": "Weird",
    },
  },
  {
    id: "magic",
    name: "Magic",
    className: "cleric",
    spells: {
      "1": "Identify",
      "2": "Magic Mouth",
      "3": "Dispel Magic",
      "4": "Imbue with Spell Ability",
      "5": "Spell Resistance",
      "6": "Antimagic Field",
      "7": "Spell Turning",
      "8": "Protection from Spells",
      "9": "Mage's Disjunction",
    },
  },
  {
    id: "nobility",
    name: "Nobility",
    className: "cleric",
    spells: {
      "1": "Divine Favor",
      "2": "Enthrall",
      "3": "Magic Vestment",
      "4": "Discern Lies",
      "5": "Command, Greater",
      "6": "Geas/Quest",
      "7": "Repulsion",
      "8": "Demand",
      "9": "Storm of Vengeance",
    },
  },
  {
    id: "plant",
    name: "Plant",
    className: "cleric",
    spells: {
      "1": "Entangle",
      "2": "Barkskin",
      "3": "Plant Growth",
      "4": "Command Plants",
      "5": "Wall of Thorns",
      "6": "Repel Wood",
      "7": "Animate Plants",
      "8": "Control Plants",
      "9": "Shambler",
    },
  },
  {
    id: "protection",
    name: "Protection",
    className: "cleric",
    spells: {
      "1": "Sanctuary",
      "2": "Shield Other",
      "3": "Protection from Energy",
      "4": "Spell Immunity",
      "5": "Spell Resistance",
      "6": "Antimagic Field",
      "7": "Repulsion",
      "8": "Mind Blank",
      "9": "Prismatic Sphere",
    },
  },
  {
    id: "repose",
    name: "Repose",
    className: "cleric",
    spells: {
      "1": "Deathwatch",
      "2": "Gentle Repose",
      "3": "Speak with Dead",
      "4": "Death Ward",
      "5": "Slay Living",
      "6": "Undeath to Death",
      "7": "Destruction",
      "8": "Waves of Exhaustion",
      "9": "Wail of the Banshee",
    },
  },
  {
    id: "rune",
    name: "Rune",
    className: "cleric",
    spells: {
      "1": "Erase",
      "2": "Secret Page",
      "3": "Glyph of Warding",
      "4": "Explosive Runes",
      "5": "Planar Binding, Lesser",
      "6": "Glyph of Warding, Greater",
      "7": "Instant Summons",
      "8": "Symbol of Death",
      "9": "Teleportation Circle",
    },
  },
  {
    id: "strength",
    name: "Strength",
    className: "cleric",
    spells: {
      "1": "Enlarge Person",
      "2": "Bull's Strength",
      "3": "Magic Vestment",
      "4": "Spell Immunity",
      "5": "Righteous Might",
      "6": "Stoneskin",
      "7": "Grasping Hand",
      "8": "Clenched Fist",
      "9": "Crushing Hand",
    },
  },
  {
    id: "sun",
    name: "Sun",
    className: "cleric",
    spells: {
      "1": "Endure Elements",
      "2": "Heat Metal",
      "3": "Searing Light",
      "4": "Fire Shield",
      "5": "Flame Strike",
      "6": "Fire Seeds",
      "7": "Sunbeam",
      "8": "Sunburst",
      "9": "Prismatic Sphere",
    },
  },
  {
    id: "travel",
    name: "Travel",
    className: "cleric",
    spells: {
      "1": "Longstrider",
      "2": "Locate Object",
      "3": "Fly",
      "4": "Dimension Door",
      "5": "Teleport",
      "6": "Find the Path",
      "7": "Teleport, Greater",
      "8": "Phase Door",
      "9": "Astral Projection",
    },
  },
  {
    id: "trickery",
    name: "Trickery",
    className: "cleric",
    spells: {
      "1": "Disguise Self",
      "2": "Invisibility",
      "3": "Nondetection",
      "4": "Confusion",
      "5": "False Vision",
      "6": "Mislead",
      "7": "Screen",
      "8": "Invisibility, Mass",
      "9": "Time Stop",
    },
  },
  {
    id: "war",
    name: "War",
    className: "cleric",
    spells: {
      "1": "Magic Weapon",
      "2": "Spiritual Weapon",
      "3": "Magic Vestment",
      "4": "Divine Power",
      "5": "Flame Strike",
      "6": "Blade Barrier",
      "7": "Power Word Blind",
      "8": "Power Word Stun",
      "9": "Power Word Kill",
    },
  },
  {
    id: "water",
    name: "Water",
    className: "cleric",
    spells: {
      "1": "Obscuring Mist",
      "2": "Fog Cloud",
      "3": "Water Breathing",
      "4": "Control Water",
      "5": "Ice Storm",
      "6": "Cone of Cold",
      "7": "Elemental Body IV",
      "8": "Horrid Wilting",
      "9": "Elemental Swarm",
    },
    spellNotes: {
      "7": "water only",
      "9": "water spell only",
    },
  },
  {
    id: "weather",
    name: "Weather",
    className: "cleric",
    spells: {
      "1": "Obscuring Mist",
      "2": "Fog Cloud",
      "3": "Call Lightning",
      "4": "Sleet Storm",
      "5": "Ice Storm",
      "6": "Control Winds",
      "7": "Control Weather",
      "8": "Whirlwind",
      "9": "Storm of Vengeance",
    },
  },
];
export const CORE_BLOODLINE_SPELLS: SpellBloodlineDefinition[] = [
  {
    id: "aberrant",
    name: "Aberrant",
    bonusSpells: [
      "Enlarge Person",
      "See Invisibility",
      "Tongues",
      "Black Tentacles",
      "Feeblemind",
      "Veil",
      "Plane Shift",
      "Mind Blank",
      "Shapechange",
    ],
  },
  {
    id: "abyssal",
    name: "Abyssal",
    bonusSpells: [
      "Cause Fear",
      "Bull's Strength",
      "Rage",
      "Stoneskin",
      "Dismissal",
      "Transformation",
      "Teleport, Greater",
      "Unholy Aura",
      "Summon Monster 9",
    ],
  },
  {
    id: "arcane",
    name: "Arcane",
    bonusSpells: [
      "Identify",
      "Invisibility",
      "Dispel Magic",
      "Dimension Door",
      "Overland Flight",
      "True Seeing",
      "Teleport, Greater",
      "Power Word Stun",
      "Wish",
    ],
  },
  {
    id: "celestial",
    name: "Celestial",
    bonusSpells: [
      "Bless",
      "Resist Energy",
      "Magic Circle against Evil",
      "Remove Curse",
      "Flame Strike",
      "Dispel Magic, Greater",
      "Banishment",
      "Sunburst",
      "Gate",
    ],
  },
  {
    id: "destined",
    name: "Destined",
    bonusSpells: [
      "Alarm",
      "Blur",
      "Protection from Energy",
      "Freedom of Movement",
      "Break Enchantment",
      "Mislead",
      "Spell Turning",
      "Moment of Prescience",
      "Foresight",
    ],
  },
  {
    id: "draconic",
    name: "Draconic",
    bonusSpells: [
      "Mage Armor",
      "Resist Energy",
      "Fly",
      "Fear",
      "Spell Resistance",
      "Form of the Dragon I",
      "Form of the Dragon II",
      "Form of the Dragon III",
      "Wish",
    ],
  },
  {
    id: "elemental",
    name: "Elemental",
    bonusSpells: [
      "Burning Hands",
      "Scorching Ray",
      "Protection from Energy",
      "Elemental Body I",
      "Elemental Body II",
      "Elemental Body III",
      "Elemental Body IV",
      "Summon Monster 8",
      "Elemental Swarm",
    ],
    spellNotes: {
      "1": "Uses the energy type of your chosen element.",
      "2": "Uses the energy type of your chosen element.",
      "4": "Chosen element only.",
      "5": "Chosen element only.",
      "6": "Chosen element only.",
      "7": "Chosen element only.",
      "8": "Elementals only.",
      "9": "Chosen element only.",
    },
  },
  {
    id: "fey",
    name: "Fey",
    bonusSpells: [
      "Entangle",
      "Hideous Laughter",
      "Deep Slumber",
      "Poison",
      "Tree Stride",
      "Mislead",
      "Phase Door",
      "Irresistible Dance",
      "Shapechange",
    ],
  },
  {
    id: "infernal",
    name: "Infernal",
    bonusSpells: [
      "Protection from Good",
      "Scorching Ray",
      "Suggestion",
      "Charm Monster",
      "Dominate Person",
      "Planar Binding",
      "Teleport, Greater",
      "Power Word Stun",
      "Meteor Swarm",
    ],
    spellNotes: {
      "6": "Devils and creatures with the fiendish template only.",
    },
  },
  {
    id: "undead",
    name: "Undead",
    bonusSpells: [
      "Chill Touch",
      "False Life",
      "Vampiric Touch",
      "Animate Dead",
      "Waves of Fatigue",
      "Undeath to Death",
      "Finger of Death",
      "Horrid Wilting",
      "Energy Drain",
    ],
  },
];
