import type { MagicItemDefinition } from "./magic-item-types";
import {
  acBonusChain,
  allSavesChain,
  enhancementAbilityChain,
  item,
  multiSkillBonusItem,
  skillBonusItem,
  speedItem,
} from "./magic-item-helpers";

const HEAD_ITEMS: MagicItemDefinition[] = [
  ...enhancementAbilityChain({
    key: "int",
    sourceBase: "Headband of Vast Intelligence",
    itemBaseName: "Headband of Vast Intelligence",
    slot: "head",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  ...enhancementAbilityChain({
    key: "wis",
    sourceBase: "Headband of Inspired Wisdom",
    itemBaseName: "Headband of Inspired Wisdom",
    slot: "head",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  ...enhancementAbilityChain({
    key: "cha",
    sourceBase: "Headband of Alluring Charisma",
    itemBaseName: "Headband of Alluring Charisma",
    slot: "head",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  item({
    id: "circlet-of-persuasion",
    name: "Circlet of Persuasion",
    slot: "head",
    weightLb: 1,
    costGp: 4500,
  }),
  item({
    id: "hat-of-disguise",
    name: "Hat of Disguise",
    slot: "head",
    weightLb: 1,
    costGp: 1800,
  }),
  item({
    id: "helm-of-comprehend-languages-and-read-magic",
    name: "Helm of Comprehend Languages and Read Magic",
    slot: "head",
    weightLb: 3,
    costGp: 5200,
  }),
  item({
    id: "helm-of-telepathy",
    name: "Helm of Telepathy",
    slot: "head",
    weightLb: 3,
    costGp: 27000,
  }),
  item({
    id: "helm-of-brilliance",
    name: "Helm of Brilliance",
    slot: "head",
    weightLb: 3,
    costGp: 125000,
  }),
  item({
    id: "phylactery-of-faithfulness",
    name: "Phylactery of Faithfulness",
    slot: "head",
    weightLb: 1,
    costGp: 1000,
  }),
  item({
    id: "phylactery-of-positive-channeling",
    name: "Phylactery of Positive Channeling",
    slot: "head",
    weightLb: 1,
    costGp: 11000,
  }),
  item({
    id: "phylactery-of-negative-channeling",
    name: "Phylactery of Negative Channeling",
    slot: "head",
    weightLb: 1,
    costGp: 11000,
  }),
  item({
    id: "helm-of-underwater-action",
    name: "Helm of Underwater Action",
    slot: "head",
    weightLb: 3,
    costGp: 24000,
  }),
  item({
    id: "mask-of-stony-demeanor",
    name: "Mask of Stony Demeanor",
    slot: "head",
    weightLb: 1,
    costGp: 500,
  }),
  item({
    id: "mask-of-the-skull",
    name: "Mask of the Skull",
    slot: "head",
    weightLb: 1,
    costGp: 22000,
  }),
];

const EYES_ITEMS: MagicItemDefinition[] = [
  skillBonusItem({
    id: "eyes-of-eagle",
    name: "Eyes of the Eagle",
    slot: "eyes",
    weightLb: 0,
    costGp: 2500,
    skill: "perception",
    value: 5,
  }),
  skillBonusItem({
    id: "lenses-of-detection",
    name: "Lenses of Detection",
    slot: "eyes",
    weightLb: 0,
    costGp: 3500,
    skill: "perception",
    value: 5,
  }),
  item({
    id: "eyes-of-charming",
    name: "Eyes of Charming",
    slot: "eyes",
    weightLb: 0,
    costGp: 56000,
  }),
  item({
    id: "goggles-of-minute-seeing",
    name: "Goggles of Minute Seeing",
    slot: "eyes",
    weightLb: 0,
    costGp: 2500,
  }),
  item({
    id: "goggles-of-night",
    name: "Goggles of Night",
    slot: "eyes",
    weightLb: 0,
    costGp: 12000,
  }),
  item({
    id: "gem-of-seeing",
    name: "Gem of Seeing",
    slot: "eyes",
    weightLb: 0,
    costGp: 75000,
  }),
  item({
    id: "goggles-of-truesight",
    name: "Goggles of Truesight",
    slot: "eyes",
    weightLb: 0,
    costGp: 75000,
  }),
  item({
    id: "deathwatch-eyes",
    name: "Deathwatch Eyes",
    slot: "eyes",
    weightLb: 0,
    costGp: 2000,
  }),
];

const NECK_ITEMS: MagicItemDefinition[] = [
  ...acBonusChain({
    slug: "amulet-of-natural-armor",
    nameBase: "Amulet of Natural Armor",
    slot: "neck",
    weightLb: 0,
    values: [1, 2, 3, 4, 5],
    costs: [2000, 8000, 18000, 32000, 50000],
    type: "natural-armor",
  }),
  ...enhancementAbilityChain({
    key: "wis",
    sourceBase: "Periapt of Wisdom",
    itemBaseName: "Periapt of Wisdom",
    slot: "neck",
    weightLb: 0,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  item({
    id: "amulet-of-mighty-fists-1",
    name: "Amulet of Mighty Fists +1",
    slot: "neck",
    weightLb: 0,
    costGp: 4000,
  }),
  item({
    id: "amulet-of-mighty-fists-2",
    name: "Amulet of Mighty Fists +2",
    slot: "neck",
    weightLb: 0,
    costGp: 16000,
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 2,
    downgradeToId: "amulet-of-mighty-fists-1",
    upgradeToId: "amulet-of-mighty-fists-3",
  }),
  item({
    id: "amulet-of-mighty-fists-3",
    name: "Amulet of Mighty Fists +3",
    slot: "neck",
    weightLb: 0,
    costGp: 36000,
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 3,
    downgradeToId: "amulet-of-mighty-fists-2",
    upgradeToId: "amulet-of-mighty-fists-4",
  }),
  item({
    id: "amulet-of-mighty-fists-4",
    name: "Amulet of Mighty Fists +4",
    slot: "neck",
    weightLb: 0,
    costGp: 64000,
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 4,
    downgradeToId: "amulet-of-mighty-fists-3",
    upgradeToId: "amulet-of-mighty-fists-5",
  }),
  item({
    id: "amulet-of-mighty-fists-5",
    name: "Amulet of Mighty Fists +5",
    slot: "neck",
    weightLb: 0,
    costGp: 100000,
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 5,
    downgradeToId: "amulet-of-mighty-fists-4",
  }),
  item({
    id: "brooch-of-shielding",
    name: "Brooch of Shielding",
    slot: "neck",
    weightLb: 0,
    costGp: 1500,
  }),
  item({
    id: "necklace-of-adaptation",
    name: "Necklace of Adaptation",
    slot: "neck",
    weightLb: 0,
    costGp: 9000,
  }),
  item({
    id: "necklace-of-fireballs-type-i",
    name: "Necklace of Fireballs Type I",
    slot: "neck",
    weightLb: 0,
    costGp: 1650,
  }),
  item({
    id: "necklace-of-fireballs-type-ii",
    name: "Necklace of Fireballs Type II",
    slot: "neck",
    weightLb: 0,
    costGp: 2700,
  }),
  item({
    id: "necklace-of-fireballs-type-iii",
    name: "Necklace of Fireballs Type III",
    slot: "neck",
    weightLb: 0,
    costGp: 4350,
  }),
  item({
    id: "necklace-of-fireballs-type-iv",
    name: "Necklace of Fireballs Type IV",
    slot: "neck",
    weightLb: 0,
    costGp: 5400,
  }),
  item({
    id: "necklace-of-fireballs-type-v",
    name: "Necklace of Fireballs Type V",
    slot: "neck",
    weightLb: 0,
    costGp: 6150,
  }),
  item({
    id: "necklace-of-fireballs-type-vi",
    name: "Necklace of Fireballs Type VI",
    slot: "neck",
    weightLb: 0,
    costGp: 8700,
  }),
  item({
    id: "periapt-of-health",
    name: "Periapt of Health",
    slot: "neck",
    weightLb: 0,
    costGp: 7500,
  }),
  item({
    id: "scarab-of-protection",
    name: "Scarab of Protection",
    slot: "neck",
    weightLb: 0,
    costGp: 38000,
  }),
  item({
    id: "periapt-of-proof-against-poison",
    name: "Periapt of Proof against Poison",
    slot: "neck",
    weightLb: 0,
    costGp: 27000,
  }),
  item({
    id: "amulet-of-proof-against-detection-and-location",
    name: "Amulet of Proof against Detection and Location",
    slot: "neck",
    weightLb: 0,
    costGp: 35000,
  }),
];

const SHOULDERS_ITEMS: MagicItemDefinition[] = [
  ...allSavesChain({
    slug: "cloak-of-resistance",
    nameBase: "Cloak of Resistance",
    slot: "shoulders",
    weightLb: 1,
    values: [1, 2, 3, 4, 5],
    costs: [1000, 4000, 9000, 16000, 25000],
  }),
  skillBonusItem({
    id: "cloak-of-elvenkind",
    name: "Cloak of Elvenkind",
    slot: "shoulders",
    weightLb: 1,
    costGp: 2500,
    skill: "stealth",
    value: 5,
  }),
  item({
    id: "cape-of-the-mountebank",
    name: "Cape of the Mountebank",
    slot: "shoulders",
    weightLb: 1,
    costGp: 10800,
  }),
  item({
    id: "cloak-of-arachnida",
    name: "Cloak of Arachnida",
    slot: "shoulders",
    weightLb: 1,
    costGp: 14000,
  }),
  item({
    id: "cloak-of-etherealness",
    name: "Cloak of Etherealness",
    slot: "shoulders",
    weightLb: 1,
    costGp: 55000,
  }),
  item({
    id: "cloak-of-the-manta-ray",
    name: "Cloak of the Manta Ray",
    slot: "shoulders",
    weightLb: 1,
    costGp: 7200,
  }),
  item({
    id: "major-cloak-of-displacement",
    name: "Major Cloak of Displacement",
    slot: "shoulders",
    weightLb: 1,
    costGp: 50000,
  }),
  item({
    id: "minor-cloak-of-displacement",
    name: "Minor Cloak of Displacement",
    slot: "shoulders",
    weightLb: 1,
    costGp: 24000,
  }),
  item({
    id: "wings-of-flying",
    name: "Wings of Flying",
    slot: "shoulders",
    weightLb: 1,
    costGp: 54000,
  }),
];

const CHEST_ITEMS: MagicItemDefinition[] = [
  multiSkillBonusItem({
    id: "vest-of-escape",
    name: "Vest of Escape",
    slot: "chest",
    weightLb: 1,
    costGp: 5200,
    skills: ["disable-device", "escape-artist", "sleight-of-hand"],
    value: 4,
  }),
  item({
    id: "cassock-of-the-clergy",
    name: "Cassock of the Clergy",
    slot: "chest",
    weightLb: 1,
    costGp: 4600,
  }),
  item({
    id: "medallion-of-thoughts",
    name: "Medallion of Thoughts",
    slot: "chest",
    weightLb: 1,
    costGp: 12000,
  }),
  item({
    id: "scarab-breastplate",
    name: "Scarab Breastplate",
    slot: "chest",
    weightLb: 1,
    costGp: 8000,
  }),
  item({
    id: "brooch-of-instantly",
    name: "Brooch of Instantly",
    slot: "chest",
    weightLb: 1,
    costGp: 3000,
  }),
];

const BODY_ITEMS: MagicItemDefinition[] = [
  item({
    id: "druids-vestment",
    name: "Druid's Vestment",
    slot: "body",
    weightLb: 1,
    costGp: 3750,
  }),
  item({
    id: "monks-robe",
    name: "Monk's Robe",
    slot: "body",
    weightLb: 1,
    costGp: 13000,
  }),
  item({
    id: "robe-of-blending",
    name: "Robe of Blending",
    slot: "body",
    weightLb: 1,
    costGp: 30000,
  }),
  item({
    id: "robe-of-bones",
    name: "Robe of Bones",
    slot: "body",
    weightLb: 1,
    costGp: 2400,
  }),
  skillBonusItem({
    id: "robe-of-eyes",
    name: "Robe of Eyes",
    slot: "body",
    weightLb: 1,
    costGp: 120000,
    skill: "perception",
    value: 10,
  }),
  item({
    id: "robe-of-scintillating-colors",
    name: "Robe of Scintillating Colors",
    slot: "body",
    weightLb: 1,
    costGp: 27000,
  }),
  item({
    id: "robe-of-the-archmagi",
    name: "Robe of the Archmagi",
    slot: "body",
    weightLb: 1,
    costGp: 75000,
    modifiers: [
      {
        target: "ac",
        type: "armor",
        value: 5,
        source: "Robe of the Archmagi",
        pack: "core",
      },
      {
        target: "save.all",
        type: "resistance",
        value: 5,
        source: "Robe of the Archmagi",
        pack: "core",
      },
    ],
  }),
  item({
    id: "robe-of-useful-items",
    name: "Robe of Useful Items",
    slot: "body",
    weightLb: 1,
    costGp: 7000,
  }),
  item({
    id: "robe-of-stars",
    name: "Robe of Stars",
    slot: "body",
    weightLb: 1,
    costGp: 58000,
  }),
  item({
    id: "robe-of-the-lordly-might",
    name: "Robe of the Lordly Might",
    slot: "body",
    weightLb: 1,
    costGp: 22000,
  }),
];

const TORSO_ITEMS: MagicItemDefinition[] = [
  item({
    id: "corset-of-delicate-moves",
    name: "Corset of Delicate Moves",
    slot: "torso",
    weightLb: 1,
    costGp: 4000,
  }),
  item({
    id: "shirt-of-immolation",
    name: "Shirt of Immolation",
    slot: "torso",
    weightLb: 1,
    costGp: 10000,
  }),
  item({
    id: "vest-of-stable-mutation",
    name: "Vest of Stable Mutation",
    slot: "torso",
    weightLb: 1,
    costGp: 20000,
  }),
  item({
    id: "vest-of-surgery",
    name: "Vest of Surgery",
    slot: "torso",
    weightLb: 1,
    costGp: 10000,
  }),
];

const BELT_ITEMS: MagicItemDefinition[] = [
  ...enhancementAbilityChain({
    key: "str",
    sourceBase: "Belt of Giant Strength",
    itemBaseName: "Belt of Giant Strength",
    slot: "belt",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  ...enhancementAbilityChain({
    key: "con",
    sourceBase: "Belt of Mighty Constitution",
    itemBaseName: "Belt of Mighty Constitution",
    slot: "belt",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  item({
    id: "belt-of-dwarvenkind",
    name: "Belt of Dwarvenkind",
    slot: "belt",
    weightLb: 1,
    costGp: 14900,
  }),
  item({
    id: "monks-belt",
    name: "Monk's Belt",
    slot: "belt",
    weightLb: 1,
    costGp: 13000,
  }),
  item({
    id: "belt-of-tumbling",
    name: "Belt of Tumbling",
    slot: "belt",
    weightLb: 1,
    costGp: 800,
  }),
  item({
    id: "belt-of-battlefield-clarity",
    name: "Belt of Battlefield Clarity",
    slot: "belt",
    weightLb: 1,
    costGp: 5000,
  }),
  item({
    id: "belt-of-physical-might-2",
    name: "Belt of Physical Might +2",
    slot: "belt",
    weightLb: 1,
    costGp: 10000,
  }),
];

const WRISTS_ITEMS: MagicItemDefinition[] = [
  ...acBonusChain({
    slug: "bracers-of-armor",
    nameBase: "Bracers of Armor",
    slot: "wrists",
    weightLb: 1,
    values: [1, 2, 3, 4, 5, 6, 7, 8],
    costs: [1000, 4000, 9000, 16000, 25000, 36000, 49000, 64000],
    type: "armor",
  }),
  item({
    id: "bracelets-of-friends",
    name: "Bracelets of Friends",
    slot: "wrists",
    weightLb: 0,
    costGp: 19000,
  }),
  item({
    id: "bracers-of-archery-lesser",
    name: "Bracers of Archery, Lesser",
    slot: "wrists",
    weightLb: 1,
    costGp: 5000,
  }),
  item({
    id: "bracers-of-archery-greater",
    name: "Bracers of Archery, Greater",
    slot: "wrists",
    weightLb: 1,
    costGp: 25000,
  }),
  item({
    id: "manacles-of-cooperation",
    name: "Manacles of Cooperation",
    slot: "wrists",
    weightLb: 2,
    costGp: 5000,
  }),
  item({
    id: "bracelet-of-mercy",
    name: "Bracelet of Mercy",
    slot: "wrists",
    weightLb: 0,
    costGp: 15000,
  }),
];

const HANDS_ITEMS: MagicItemDefinition[] = [
  ...enhancementAbilityChain({
    key: "dex",
    sourceBase: "Gloves of Dexterity",
    itemBaseName: "Gloves of Dexterity",
    slot: "hands",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
  }),
  item({
    id: "gauntlets-of-ogre-power",
    name: "Gauntlets of Ogre Power",
    slot: "hands",
    weightLb: 1,
    costGp: 4000,
    modifiers: [
      {
        target: "str",
        type: "enhancement",
        value: 2,
        source: "Gauntlets of Ogre Power",
        pack: "core",
      },
    ],
  }),
  multiSkillBonusItem({
    id: "gloves-of-swimming-and-climbing",
    name: "Gloves of Swimming and Climbing",
    slot: "hands",
    weightLb: 1,
    costGp: 6250,
    skills: ["climb", "swim"],
    value: 5,
  }),
  item({
    id: "gauntlet-of-rust",
    name: "Gauntlet of Rust",
    slot: "hands",
    weightLb: 1,
    costGp: 11500,
  }),
  item({
    id: "gloves-of-arrow-snaring",
    name: "Gloves of Arrow Snaring",
    slot: "hands",
    weightLb: 1,
    costGp: 4000,
  }),
  item({
    id: "gloves-of-storing",
    name: "Gloves of Storing",
    slot: "hands",
    weightLb: 1,
    costGp: 10000,
  }),
  item({
    id: "gloves-of-reconnaissance",
    name: "Gloves of Reconnaissance",
    slot: "hands",
    weightLb: 1,
    costGp: 2000,
  }),
  item({
    id: "gloves-of-shaping",
    name: "Gloves of Shaping",
    slot: "hands",
    weightLb: 1,
    costGp: 10000,
  }),
];

const FEET_ITEMS: MagicItemDefinition[] = [
  skillBonusItem({
    id: "boots-of-elvenkind",
    name: "Boots of Elvenkind",
    slot: "feet",
    weightLb: 1,
    costGp: 2500,
    skill: "stealth",
    value: 5,
  }),
  speedItem({
    id: "boots-of-striding-and-springing",
    name: "Boots of Striding and Springing",
    slot: "feet",
    weightLb: 1,
    costGp: 5500,
    value: 10,
  }),
  item({
    id: "boots-of-levitation",
    name: "Boots of Levitation",
    slot: "feet",
    weightLb: 1,
    costGp: 7500,
  }),
  item({
    id: "boots-of-speed",
    name: "Boots of Speed",
    slot: "feet",
    weightLb: 1,
    costGp: 12000,
  }),
  item({
    id: "boots-of-teleportation",
    name: "Boots of Teleportation",
    slot: "feet",
    weightLb: 1,
    costGp: 49000,
  }),
  item({
    id: "slippers-of-spider-climbing",
    name: "Slippers of Spider Climbing",
    slot: "feet",
    weightLb: 1,
    costGp: 4800,
  }),
  item({
    id: "winged-boots",
    name: "Winged Boots",
    slot: "feet",
    weightLb: 1,
    costGp: 16000,
  }),
  item({
    id: "horseshoes-of-speed",
    name: "Horseshoes of Speed",
    slot: "feet",
    weightLb: 4,
    costGp: 3000,
  }),
  item({
    id: "sandals-of-quick-reaction",
    name: "Sandals of Quick Reaction",
    slot: "feet",
    weightLb: 1,
    costGp: 3500,
    modifiers: [
      {
        target: "init",
        type: "competence",
        value: 2,
        source: "Sandals of Quick Reaction",
        pack: "core",
      },
    ],
  }),
];

const RING_ITEMS: MagicItemDefinition[] = [
  ...acBonusChain({
    slug: "ring-of-protection",
    nameBase: "Ring of Protection",
    slot: "ring",
    weightLb: 0,
    values: [1, 2, 3, 4, 5],
    costs: [2000, 8000, 18000, 32000, 50000],
    type: "deflection",
  }),
  skillBonusItem({
    id: "ring-of-climbing",
    name: "Ring of Climbing",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    skill: "climb",
    value: 5,
  }),
  skillBonusItem({
    id: "ring-of-jumping",
    name: "Ring of Jumping",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    skill: "acrobatics",
    value: 5,
  }),
  skillBonusItem({
    id: "ring-of-swimming",
    name: "Ring of Swimming",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    skill: "swim",
    value: 5,
  }),
  item({
    id: "ring-of-blinking",
    name: "Ring of Blinking",
    slot: "ring",
    weightLb: 0,
    costGp: 27000,
  }),
  item({
    id: "ring-of-chameleon-power",
    name: "Ring of Chameleon Power",
    slot: "ring",
    weightLb: 0,
    costGp: 12700,
  }),
  item({
    id: "ring-of-counterspells",
    name: "Ring of Counterspells",
    slot: "ring",
    weightLb: 0,
    costGp: 4000,
  }),
  item({
    id: "ring-of-djinni-calling",
    name: "Ring of Djinni Calling",
    slot: "ring",
    weightLb: 0,
    costGp: 125000,
  }),
  item({
    id: "ring-of-elemental-command-air",
    name: "Ring of Elemental Command (Air)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
  }),
  item({
    id: "ring-of-elemental-command-earth",
    name: "Ring of Elemental Command (Earth)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
  }),
  item({
    id: "ring-of-elemental-command-fire",
    name: "Ring of Elemental Command (Fire)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
  }),
  item({
    id: "ring-of-elemental-command-water",
    name: "Ring of Elemental Command (Water)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
  }),
  item({
    id: "ring-of-evasion",
    name: "Ring of Evasion",
    slot: "ring",
    weightLb: 0,
    costGp: 25000,
  }),
  item({
    id: "ring-of-feather-falling",
    name: "Ring of Feather Falling",
    slot: "ring",
    weightLb: 0,
    costGp: 2200,
  }),
  item({
    id: "ring-of-force-shield",
    name: "Ring of Force Shield",
    slot: "ring",
    weightLb: 0,
    costGp: 8500,
  }),
  item({
    id: "ring-of-freedom-of-movement",
    name: "Ring of Freedom of Movement",
    slot: "ring",
    weightLb: 0,
    costGp: 40000,
  }),
  item({
    id: "ring-of-invisibility",
    name: "Ring of Invisibility",
    slot: "ring",
    weightLb: 0,
    costGp: 20000,
  }),
  item({
    id: "ring-of-mind-shielding",
    name: "Ring of Mind Shielding",
    slot: "ring",
    weightLb: 0,
    costGp: 8000,
  }),
  item({
    id: "ring-of-ram",
    name: "Ring of the Ram",
    slot: "ring",
    weightLb: 0,
    costGp: 8600,
  }),
  item({
    id: "ring-of-regeneration",
    name: "Ring of Regeneration",
    slot: "ring",
    weightLb: 0,
    costGp: 90000,
  }),
  item({
    id: "ring-of-shooting-stars",
    name: "Ring of Shooting Stars",
    slot: "ring",
    weightLb: 0,
    costGp: 50000,
  }),
  item({
    id: "ring-of-spell-storing",
    name: "Ring of Spell Storing",
    slot: "ring",
    weightLb: 0,
    costGp: 50000,
  }),
  item({
    id: "ring-of-spell-turning",
    name: "Ring of Spell Turning",
    slot: "ring",
    weightLb: 0,
    costGp: 100000,
  }),
  item({
    id: "ring-of-sustenance",
    name: "Ring of Sustenance",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
  }),
  item({
    id: "ring-of-telekinesis",
    name: "Ring of Telekinesis",
    slot: "ring",
    weightLb: 0,
    costGp: 75000,
  }),
  item({
    id: "ring-of-three-wishes",
    name: "Ring of Three Wishes",
    slot: "ring",
    weightLb: 0,
    costGp: 120000,
  }),
  item({
    id: "ring-of-wizardry-i",
    name: "Ring of Wizardry I",
    slot: "ring",
    weightLb: 0,
    costGp: 20000,
  }),
  item({
    id: "ring-of-wizardry-ii",
    name: "Ring of Wizardry II",
    slot: "ring",
    weightLb: 0,
    costGp: 40000,
  }),
  item({
    id: "ring-of-wizardry-iii",
    name: "Ring of Wizardry III",
    slot: "ring",
    weightLb: 0,
    costGp: 70000,
  }),
  item({
    id: "ring-of-wizardry-iv",
    name: "Ring of Wizardry IV",
    slot: "ring",
    weightLb: 0,
    costGp: 100000,
  }),
  item({
    id: "ring-of-x-ray-vision",
    name: "Ring of X-Ray Vision",
    slot: "ring",
    weightLb: 0,
    costGp: 25000,
  }),
  item({
    id: "ring-of-animal-friendship",
    name: "Ring of Animal Friendship",
    slot: "ring",
    weightLb: 0,
    costGp: 10800,
  }),
  item({
    id: "ring-of-energy-resistance-minor",
    name: "Ring of Energy Resistance, Minor",
    slot: "ring",
    weightLb: 0,
    costGp: 12000,
  }),
  item({
    id: "ring-of-energy-resistance-major",
    name: "Ring of Energy Resistance, Major",
    slot: "ring",
    weightLb: 0,
    costGp: 28000,
  }),
  item({
    id: "ring-of-the-ecclesiarch",
    name: "Ring of the Ecclesiarch",
    slot: "ring",
    weightLb: 0,
    costGp: 14000,
  }),
];

export const CORE_MAGIC_ITEMS: MagicItemDefinition[] = [
  ...HEAD_ITEMS,
  ...EYES_ITEMS,
  ...NECK_ITEMS,
  ...SHOULDERS_ITEMS,
  ...CHEST_ITEMS,
  ...BODY_ITEMS,
  ...TORSO_ITEMS,
  ...BELT_ITEMS,
  ...WRISTS_ITEMS,
  ...HANDS_ITEMS,
  ...FEET_ITEMS,
  ...RING_ITEMS,
];
