import type { MagicItemDefinition } from "./shared";
import { allSavesChain, item, skillBonusItem } from "./helpers";

export const SHOULDERS_ITEMS: MagicItemDefinition[] = [
  ...allSavesChain({
    slug: "cloak-of-resistance",
    nameBase: "Cloak of Resistance",
    slot: "shoulders",
    weightLb: 1,
    values: [1, 2, 3, 4, 5],
    costs: [1000, 4000, 9000, 16000, 25000],
    tags: ["saves"],
  }),
  skillBonusItem({
    id: "cloak-of-elvenkind",
    name: "Cloak of Elvenkind",
    slot: "shoulders",
    weightLb: 1,
    costGp: 2500,
    skill: "stealth",
    value: 5,
    tags: ["stealth"],
  }),
  item({
    id: "cape-of-the-mountebank",
    name: "Cape of the Mountebank",
    slot: "shoulders",
    weightLb: 1,
    costGp: 10800,
    tags: ["teleportation"],
  }),
  item({
    id: "cloak-of-arachnida",
    name: "Cloak of Arachnida",
    slot: "shoulders",
    weightLb: 1,
    costGp: 14000,
    tags: ["climb", "poison"],
  }),
  item({
    id: "cloak-of-etherealness",
    name: "Cloak of Etherealness",
    slot: "shoulders",
    weightLb: 1,
    costGp: 55000,
    tags: ["ethereal"],
  }),
  item({
    id: "cloak-of-the-manta-ray",
    name: "Cloak of the Manta Ray",
    slot: "shoulders",
    weightLb: 1,
    costGp: 7200,
    tags: ["water"],
  }),
  item({
    id: "major-cloak-of-displacement",
    name: "Major Cloak of Displacement",
    slot: "shoulders",
    weightLb: 1,
    costGp: 50000,
    tags: ["illusion"],
    automationStatus: "manual",
    automationNotes: "Miss chance not yet modeled.",
  }),
  item({
    id: "minor-cloak-of-displacement",
    name: "Minor Cloak of Displacement",
    slot: "shoulders",
    weightLb: 1,
    costGp: 24000,
    tags: ["illusion"],
    automationStatus: "manual",
    automationNotes: "Miss chance not yet modeled.",
  }),
  item({
    id: "wings-of-flying",
    name: "Wings of Flying",
    slot: "shoulders",
    weightLb: 1,
    costGp: 54000,
    tags: ["flight"],
  }),
];
