import type { MagicItemDefinition } from "./shared";
import { enhancementAbilityChain, item } from "./helpers";

export const HEAD_ITEMS: MagicItemDefinition[] = [
  ...enhancementAbilityChain({
    key: "int",
    sourceBase: "Headband of Vast Intelligence",
    itemBaseName: "Headband of Vast Intelligence",
    slot: "head",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
    automationStatus: "partial",
    automationNotes:
      "Int enhancement is automated; granted-skill rules are not yet modeled.",
    tags: ["ability", "intelligence", "headband"],
  }),
  ...enhancementAbilityChain({
    key: "wis",
    sourceBase: "Headband of Inspired Wisdom",
    itemBaseName: "Headband of Inspired Wisdom",
    slot: "head",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
    tags: ["ability", "wisdom", "headband"],
  }),
  ...enhancementAbilityChain({
    key: "cha",
    sourceBase: "Headband of Alluring Charisma",
    itemBaseName: "Headband of Alluring Charisma",
    slot: "head",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
    tags: ["ability", "charisma", "headband"],
  }),
  item({
    id: "circlet-of-persuasion",
    name: "Circlet of Persuasion",
    slot: "head",
    weightLb: 1,
    costGp: 4500,
    tags: ["social"],
    automationStatus: "manual",
    automationNotes:
      "Competence bonus to Charisma-based checks not yet modeled.",
  }),
  item({
    id: "hat-of-disguise",
    name: "Hat of Disguise",
    slot: "head",
    weightLb: 1,
    costGp: 1800,
    tags: ["illusion", "disguise"],
  }),
  item({
    id: "helm-of-comprehend-languages-and-read-magic",
    name: "Helm of Comprehend Languages and Read Magic",
    slot: "head",
    weightLb: 3,
    costGp: 5200,
    tags: ["utility", "divination"],
  }),
  item({
    id: "helm-of-telepathy",
    name: "Helm of Telepathy",
    slot: "head",
    weightLb: 3,
    costGp: 27000,
    tags: ["mind-affecting", "telepathy"],
  }),
  item({
    id: "helm-of-brilliance",
    name: "Helm of Brilliance",
    slot: "head",
    weightLb: 3,
    costGp: 125000,
    tags: ["fire", "light"],
  }),
  item({
    id: "phylactery-of-faithfulness",
    name: "Phylactery of Faithfulness",
    slot: "head",
    weightLb: 1,
    costGp: 1000,
    tags: ["divine"],
  }),
  item({
    id: "phylactery-of-positive-channeling",
    name: "Phylactery of Positive Channeling",
    slot: "head",
    weightLb: 1,
    costGp: 11000,
    tags: ["channel-energy"],
    automationStatus: "manual",
    automationNotes: "Channel energy modification not yet modeled.",
  }),
  item({
    id: "phylactery-of-negative-channeling",
    name: "Phylactery of Negative Channeling",
    slot: "head",
    weightLb: 1,
    costGp: 11000,
    tags: ["channel-energy"],
    automationStatus: "manual",
    automationNotes: "Channel energy modification not yet modeled.",
  }),
  item({
    id: "helm-of-underwater-action",
    name: "Helm of Underwater Action",
    slot: "head",
    weightLb: 3,
    costGp: 24000,
    tags: ["water"],
  }),
  item({
    id: "mask-of-stony-demeanor",
    name: "Mask of Stony Demeanor",
    slot: "head",
    weightLb: 1,
    costGp: 500,
    tags: ["social"],
  }),
  item({
    id: "mask-of-the-skull",
    name: "Mask of the Skull",
    slot: "head",
    weightLb: 1,
    costGp: 22000,
    tags: ["necromancy"],
  }),
];
