import type { MagicItemDefinition } from "./shared";
import { enhancementAbilityChain, item } from "./helpers";

export const BELT_ITEMS: MagicItemDefinition[] = [
  ...enhancementAbilityChain({
    key: "str",
    sourceBase: "Belt of Giant Strength",
    itemBaseName: "Belt of Giant Strength",
    slot: "belt",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
    tags: ["ability", "strength"],
  }),
  ...enhancementAbilityChain({
    key: "con",
    sourceBase: "Belt of Mighty Constitution",
    itemBaseName: "Belt of Mighty Constitution",
    slot: "belt",
    weightLb: 1,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
    tags: ["ability", "constitution"],
  }),
  item({
    id: "belt-of-dwarvenkind",
    name: "Belt of Dwarvenkind",
    slot: "belt",
    weightLb: 1,
    costGp: 14900,
    tags: ["dwarf"],
    automationStatus: "manual",
    automationNotes: "Racial trait/style effects not yet modeled.",
  }),
  item({
    id: "monks-belt",
    name: "Monk's Belt",
    slot: "belt",
    weightLb: 1,
    costGp: 13000,
    tags: ["monk"],
    automationStatus: "manual",
    automationNotes: "Monk feature interactions not yet modeled.",
  }),
  item({
    id: "belt-of-tumbling",
    name: "Belt of Tumbling",
    slot: "belt",
    weightLb: 1,
    costGp: 800,
    tags: ["acrobatics"],
    automationStatus: "manual",
    automationNotes: "Acrobatics circumstance bonus not yet modeled.",
  }),
  item({
    id: "belt-of-battlefield-clarity",
    name: "Belt of Battlefield Clarity",
    slot: "belt",
    weightLb: 1,
    costGp: 5000,
    tags: ["martial"],
  }),
  item({
    id: "belt-of-physical-might-2",
    name: "Belt of Physical Might +2",
    slot: "belt",
    weightLb: 1,
    costGp: 10000,
    tags: ["ability"],
    automationStatus: "manual",
    automationNotes: "Compound physical stat selections not yet modeled.",
  }),
];
