import type { MagicItemDefinition } from "./shared";
import { acBonusChain, item, skillBonusItem } from "./helpers";

export const RING_ITEMS: MagicItemDefinition[] = [
  ...acBonusChain({
    slug: "ring-of-protection",
    nameBase: "Ring of Protection",
    slot: "ring",
    weightLb: 0,
    values: [1, 2, 3, 4, 5],
    costs: [2000, 8000, 18000, 32000, 50000],
    type: "deflection",
    tags: ["ac"],
  }),
  skillBonusItem({
    id: "ring-of-climbing",
    name: "Ring of Climbing",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    skill: "climb",
    value: 5,
    tags: ["climb"],
  }),
  skillBonusItem({
    id: "ring-of-jumping",
    name: "Ring of Jumping",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    skill: "acrobatics",
    value: 5,
    tags: ["acrobatics"],
  }),
  skillBonusItem({
    id: "ring-of-swimming",
    name: "Ring of Swimming",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    skill: "swim",
    value: 5,
    tags: ["swim"],
  }),
  item({
    id: "ring-of-blinking",
    name: "Ring of Blinking",
    slot: "ring",
    weightLb: 0,
    costGp: 27000,
    tags: ["illusion"],
  }),
  item({
    id: "ring-of-chameleon-power",
    name: "Ring of Chameleon Power",
    slot: "ring",
    weightLb: 0,
    costGp: 12700,
    tags: ["stealth", "disguise"],
  }),
  item({
    id: "ring-of-counterspells",
    name: "Ring of Counterspells",
    slot: "ring",
    weightLb: 0,
    costGp: 4000,
    tags: ["abjuration"],
  }),
  item({
    id: "ring-of-djinni-calling",
    name: "Ring of Djinni Calling",
    slot: "ring",
    weightLb: 0,
    costGp: 125000,
    tags: ["summoning"],
  }),
  item({
    id: "ring-of-elemental-command-air",
    name: "Ring of Elemental Command (Air)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
    tags: ["elemental", "air"],
  }),
  item({
    id: "ring-of-elemental-command-earth",
    name: "Ring of Elemental Command (Earth)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
    tags: ["elemental", "earth"],
  }),
  item({
    id: "ring-of-elemental-command-fire",
    name: "Ring of Elemental Command (Fire)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
    tags: ["elemental", "fire"],
  }),
  item({
    id: "ring-of-elemental-command-water",
    name: "Ring of Elemental Command (Water)",
    slot: "ring",
    weightLb: 0,
    costGp: 200000,
    tags: ["elemental", "water"],
  }),
  item({
    id: "ring-of-evasion",
    name: "Ring of Evasion",
    slot: "ring",
    weightLb: 0,
    costGp: 25000,
    tags: ["evasion"],
    automationStatus: "manual",
    automationNotes: "Reactive save-effect features not yet modeled.",
  }),
  item({
    id: "ring-of-feather-falling",
    name: "Ring of Feather Falling",
    slot: "ring",
    weightLb: 0,
    costGp: 2200,
    tags: ["falling"],
  }),
  item({
    id: "ring-of-force-shield",
    name: "Ring of Force Shield",
    slot: "ring",
    weightLb: 0,
    costGp: 8500,
    tags: ["shield"],
    automationStatus: "manual",
    automationNotes: "Activated shield bonus not yet modeled.",
  }),
  item({
    id: "ring-of-freedom-of-movement",
    name: "Ring of Freedom of Movement",
    slot: "ring",
    weightLb: 0,
    costGp: 40000,
    tags: ["movement"],
  }),
  item({
    id: "ring-of-invisibility",
    name: "Ring of Invisibility",
    slot: "ring",
    weightLb: 0,
    costGp: 20000,
    tags: ["invisibility"],
  }),
  item({
    id: "ring-of-mind-shielding",
    name: "Ring of Mind Shielding",
    slot: "ring",
    weightLb: 0,
    costGp: 8000,
    tags: ["mind-affecting"],
  }),
  item({
    id: "ring-of-ram",
    name: "Ring of the Ram",
    slot: "ring",
    weightLb: 0,
    costGp: 8600,
    tags: ["force"],
  }),
  item({
    id: "ring-of-regeneration",
    name: "Ring of Regeneration",
    slot: "ring",
    weightLb: 0,
    costGp: 90000,
    tags: ["healing"],
    automationStatus: "manual",
    automationNotes: "Regeneration not yet modeled.",
  }),
  item({
    id: "ring-of-shooting-stars",
    name: "Ring of Shooting Stars",
    slot: "ring",
    weightLb: 0,
    costGp: 50000,
    tags: ["light", "charges"],
  }),
  item({
    id: "ring-of-spell-storing",
    name: "Ring of Spell Storing",
    slot: "ring",
    weightLb: 0,
    costGp: 50000,
    tags: ["spells"],
  }),
  item({
    id: "ring-of-spell-turning",
    name: "Ring of Spell Turning",
    slot: "ring",
    weightLb: 0,
    costGp: 100000,
    tags: ["abjuration"],
  }),
  item({
    id: "ring-of-sustenance",
    name: "Ring of Sustenance",
    slot: "ring",
    weightLb: 0,
    costGp: 2500,
    tags: ["survival"],
  }),
  item({
    id: "ring-of-telekinesis",
    name: "Ring of Telekinesis",
    slot: "ring",
    weightLb: 0,
    costGp: 75000,
    tags: ["force"],
  }),
  item({
    id: "ring-of-three-wishes",
    name: "Ring of Three Wishes",
    slot: "ring",
    weightLb: 0,
    costGp: 120000,
    tags: ["wish"],
  }),
  item({
    id: "ring-of-wizardry-i",
    name: "Ring of Wizardry I",
    slot: "ring",
    weightLb: 0,
    costGp: 20000,
    tags: ["arcane"],
    automationStatus: "manual",
    automationNotes: "Spell slot doubling not yet modeled.",
  }),
  item({
    id: "ring-of-wizardry-ii",
    name: "Ring of Wizardry II",
    slot: "ring",
    weightLb: 0,
    costGp: 40000,
    tags: ["arcane"],
    automationStatus: "manual",
    automationNotes: "Spell slot doubling not yet modeled.",
  }),
  item({
    id: "ring-of-wizardry-iii",
    name: "Ring of Wizardry III",
    slot: "ring",
    weightLb: 0,
    costGp: 70000,
    tags: ["arcane"],
    automationStatus: "manual",
    automationNotes: "Spell slot doubling not yet modeled.",
  }),
  item({
    id: "ring-of-wizardry-iv",
    name: "Ring of Wizardry IV",
    slot: "ring",
    weightLb: 0,
    costGp: 100000,
    tags: ["arcane"],
    automationStatus: "manual",
    automationNotes: "Spell slot doubling not yet modeled.",
  }),
  item({
    id: "ring-of-x-ray-vision",
    name: "Ring of X-Ray Vision",
    slot: "ring",
    weightLb: 0,
    costGp: 25000,
    tags: ["vision"],
  }),
  item({
    id: "ring-of-animal-friendship",
    name: "Ring of Animal Friendship",
    slot: "ring",
    weightLb: 0,
    costGp: 10800,
    tags: ["animal"],
  }),
  item({
    id: "ring-of-energy-resistance-minor",
    name: "Ring of Energy Resistance, Minor",
    slot: "ring",
    weightLb: 0,
    costGp: 12000,
    tags: ["energy-resistance"],
    automationStatus: "manual",
    automationNotes: "Energy resistance not yet modeled.",
  }),
  item({
    id: "ring-of-energy-resistance-major",
    name: "Ring of Energy Resistance, Major",
    slot: "ring",
    weightLb: 0,
    costGp: 28000,
    tags: ["energy-resistance"],
    automationStatus: "manual",
    automationNotes: "Energy resistance not yet modeled.",
  }),
  item({
    id: "ring-of-the-ecclesiarch",
    name: "Ring of the Ecclesiarch",
    slot: "ring",
    weightLb: 0,
    costGp: 14000,
    tags: ["divine"],
  }),
];
