import type { MagicItemDefinition } from "./shared";
import { acBonusChain, enhancementAbilityChain, item } from "./helpers";

export const NECK_ITEMS: MagicItemDefinition[] = [
  ...acBonusChain({
    slug: "amulet-of-natural-armor",
    nameBase: "Amulet of Natural Armor",
    slot: "neck",
    weightLb: 0,
    values: [1, 2, 3, 4, 5],
    costs: [2000, 8000, 18000, 32000, 50000],
    type: "natural-armor",
    tags: ["ac"],
  }),
  ...enhancementAbilityChain({
    key: "wis",
    sourceBase: "Periapt of Wisdom",
    itemBaseName: "Periapt of Wisdom",
    slot: "neck",
    weightLb: 0,
    values: [2, 4, 6],
    costs: [4000, 16000, 36000],
    tags: ["ability", "wisdom"],
  }),
  item({
    id: "amulet-of-mighty-fists-1",
    name: "Amulet of Mighty Fists +1",
    slot: "neck",
    weightLb: 0,
    costGp: 4000,
    tags: ["unarmed"],
    automationStatus: "manual",
    automationNotes: "Unarmed/natural attack enhancement not yet modeled.",
  }),
  item({
    id: "amulet-of-mighty-fists-2",
    name: "Amulet of Mighty Fists +2",
    slot: "neck",
    weightLb: 0,
    costGp: 16000,
    tags: ["unarmed"],
    automationStatus: "manual",
    automationNotes: "Unarmed/natural attack enhancement not yet modeled.",
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 2,
    downgradeToId: "amulet-of-mighty-fists-1",
    upgradeToId: "amulet-of-mighty-fists-3",
  }),
  item({
    id: "amulet-of-mighty-fists-3",
    name: "Amulet of Mighty Fists +3",
    slot: "neck",
    weightLb: 0,
    costGp: 36000,
    tags: ["unarmed"],
    automationStatus: "manual",
    automationNotes: "Unarmed/natural attack enhancement not yet modeled.",
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 3,
    downgradeToId: "amulet-of-mighty-fists-2",
    upgradeToId: "amulet-of-mighty-fists-4",
  }),
  item({
    id: "amulet-of-mighty-fists-4",
    name: "Amulet of Mighty Fists +4",
    slot: "neck",
    weightLb: 0,
    costGp: 64000,
    tags: ["unarmed"],
    automationStatus: "manual",
    automationNotes: "Unarmed/natural attack enhancement not yet modeled.",
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 4,
    downgradeToId: "amulet-of-mighty-fists-3",
    upgradeToId: "amulet-of-mighty-fists-5",
  }),
  item({
    id: "amulet-of-mighty-fists-5",
    name: "Amulet of Mighty Fists +5",
    slot: "neck",
    weightLb: 0,
    costGp: 100000,
    tags: ["unarmed"],
    automationStatus: "manual",
    automationNotes: "Unarmed/natural attack enhancement not yet modeled.",
    upgradeGroup: "amulet-of-mighty-fists",
    upgradeTier: 5,
    downgradeToId: "amulet-of-mighty-fists-4",
  }),
  item({
    id: "brooch-of-shielding",
    name: "Brooch of Shielding",
    slot: "neck",
    weightLb: 0,
    costGp: 1500,
    tags: ["abjuration"],
  }),
  item({
    id: "necklace-of-adaptation",
    name: "Necklace of Adaptation",
    slot: "neck",
    weightLb: 0,
    costGp: 9000,
    tags: ["air", "survival"],
  }),
  item({
    id: "necklace-of-fireballs-type-i",
    name: "Necklace of Fireballs Type I",
    slot: "neck",
    weightLb: 0,
    costGp: 1650,
    tags: ["fire", "charges"],
  }),
  item({
    id: "necklace-of-fireballs-type-ii",
    name: "Necklace of Fireballs Type II",
    slot: "neck",
    weightLb: 0,
    costGp: 2700,
    tags: ["fire", "charges"],
  }),
  item({
    id: "necklace-of-fireballs-type-iii",
    name: "Necklace of Fireballs Type III",
    slot: "neck",
    weightLb: 0,
    costGp: 4350,
    tags: ["fire", "charges"],
  }),
  item({
    id: "necklace-of-fireballs-type-iv",
    name: "Necklace of Fireballs Type IV",
    slot: "neck",
    weightLb: 0,
    costGp: 5400,
    tags: ["fire", "charges"],
  }),
  item({
    id: "necklace-of-fireballs-type-v",
    name: "Necklace of Fireballs Type V",
    slot: "neck",
    weightLb: 0,
    costGp: 6150,
    tags: ["fire", "charges"],
  }),
  item({
    id: "necklace-of-fireballs-type-vi",
    name: "Necklace of Fireballs Type VI",
    slot: "neck",
    weightLb: 0,
    costGp: 8700,
    tags: ["fire", "charges"],
  }),
  item({
    id: "periapt-of-health",
    name: "Periapt of Health",
    slot: "neck",
    weightLb: 0,
    costGp: 7500,
    tags: ["health"],
  }),
  item({
    id: "scarab-of-protection",
    name: "Scarab of Protection",
    slot: "neck",
    weightLb: 0,
    costGp: 38000,
    tags: ["abjuration"],
  }),
  item({
    id: "periapt-of-proof-against-poison",
    name: "Periapt of Proof against Poison",
    slot: "neck",
    weightLb: 0,
    costGp: 27000,
    tags: ["poison"],
  }),
  item({
    id: "amulet-of-proof-against-detection-and-location",
    name: "Amulet of Proof against Detection and Location",
    slot: "neck",
    weightLb: 0,
    costGp: 35000,
    tags: ["abjuration", "scrying"],
  }),
];
