import type { MagicItemDefinition } from "./shared";
import { item, skillBonusItem } from "./helpers";

export const BODY_ITEMS: MagicItemDefinition[] = [
  item({
    id: "druids-vestment",
    name: "Druid's Vestment",
    slot: "body",
    weightLb: 1,
    costGp: 3750,
    tags: ["druid"],
    automationStatus: "manual",
    automationNotes: "Wild shape enhancement not yet modeled.",
  }),
  item({
    id: "monks-robe",
    name: "Monk's Robe",
    slot: "body",
    weightLb: 1,
    costGp: 13000,
    tags: ["monk"],
    automationStatus: "manual",
    automationNotes: "Monk feature interactions not yet modeled.",
  }),
  item({
    id: "robe-of-blending",
    name: "Robe of Blending",
    slot: "body",
    weightLb: 1,
    costGp: 30000,
    tags: ["disguise"],
  }),
  item({
    id: "robe-of-bones",
    name: "Robe of Bones",
    slot: "body",
    weightLb: 1,
    costGp: 2400,
    tags: ["necromancy", "charges"],
  }),
  skillBonusItem({
    id: "robe-of-eyes",
    name: "Robe of Eyes",
    slot: "body",
    weightLb: 1,
    costGp: 120000,
    skill: "perception",
    value: 10,
    tags: ["perception"],
  }),
  item({
    id: "robe-of-scintillating-colors",
    name: "Robe of Scintillating Colors",
    slot: "body",
    weightLb: 1,
    costGp: 27000,
    tags: ["light"],
  }),
  item({
    id: "robe-of-the-archmagi",
    name: "Robe of the Archmagi",
    slot: "body",
    weightLb: 1,
    costGp: 75000,
    tags: ["arcane", "ac", "saves"],
    modifiers: [
      {
        target: "ac",
        type: "armor",
        value: 5,
        source: "Robe of the Archmagi",
        pack: "core",
      },
      {
        target: "save.all",
        type: "resistance",
        value: 5,
        source: "Robe of the Archmagi",
        pack: "core",
      },
    ],
  }),
  item({
    id: "robe-of-useful-items",
    name: "Robe of Useful Items",
    slot: "body",
    weightLb: 1,
    costGp: 7000,
    tags: ["utility"],
  }),
  item({
    id: "robe-of-stars",
    name: "Robe of Stars",
    slot: "body",
    weightLb: 1,
    costGp: 58000,
    tags: ["astral"],
  }),
  item({
    id: "robe-of-the-lordly-might",
    name: "Robe of the Lordly Might",
    slot: "body",
    weightLb: 1,
    costGp: 22000,
    tags: ["divine"],
  }),
];
