import type { MagicItemDefinition } from "./shared";
import { item, skillBonusItem, speedItem } from "./helpers";

export const FEET_ITEMS: MagicItemDefinition[] = [
  skillBonusItem({
    id: "boots-of-elvenkind",
    name: "Boots of Elvenkind",
    slot: "feet",
    weightLb: 1,
    costGp: 2500,
    skill: "stealth",
    value: 5,
    tags: ["stealth"],
  }),
  speedItem({
    id: "boots-of-striding-and-springing",
    name: "Boots of Striding and Springing",
    slot: "feet",
    weightLb: 1,
    costGp: 5500,
    value: 10,
    tags: ["speed"],
  }),
  item({
    id: "boots-of-levitation",
    name: "Boots of Levitation",
    slot: "feet",
    weightLb: 1,
    costGp: 7500,
    tags: ["levitation"],
  }),
  item({
    id: "boots-of-speed",
    name: "Boots of Speed",
    slot: "feet",
    weightLb: 1,
    costGp: 12000,
    tags: ["haste"],
    automationStatus: "manual",
    automationNotes: "Activated haste effect not yet modeled.",
  }),
  item({
    id: "boots-of-teleportation",
    name: "Boots of Teleportation",
    slot: "feet",
    weightLb: 1,
    costGp: 49000,
    tags: ["teleportation"],
  }),
  item({
    id: "slippers-of-spider-climbing",
    name: "Slippers of Spider Climbing",
    slot: "feet",
    weightLb: 1,
    costGp: 4800,
    tags: ["climb"],
  }),
  item({
    id: "winged-boots",
    name: "Winged Boots",
    slot: "feet",
    weightLb: 1,
    costGp: 16000,
    tags: ["flight"],
  }),
  item({
    id: "horseshoes-of-speed",
    name: "Horseshoes of Speed",
    slot: "feet",
    weightLb: 4,
    costGp: 3000,
    tags: ["mount"],
  }),
  item({
    id: "sandals-of-quick-reaction",
    name: "Sandals of Quick Reaction",
    slot: "feet",
    weightLb: 1,
    costGp: 3500,
    tags: ["initiative"],
    modifiers: [
      {
        target: "init",
        type: "competence",
        value: 2,
        source: "Sandals of Quick Reaction",
        pack: "core",
      },
    ],
  }),
];
