import type { MagicItemDefinition } from "./shared";
import { item, skillBonusItem } from "./helpers";

export const EYES_ITEMS: MagicItemDefinition[] = [
  skillBonusItem({
    id: "eyes-of-eagle",
    name: "Eyes of the Eagle",
    slot: "eyes",
    weightLb: 0,
    costGp: 2500,
    skill: "perception",
    value: 5,
    tags: ["perception"],
  }),
  skillBonusItem({
    id: "lenses-of-detection",
    name: "Lenses of Detection",
    slot: "eyes",
    weightLb: 0,
    costGp: 3500,
    skill: "perception",
    value: 5,
    tags: ["perception"],
  }),
  item({
    id: "eyes-of-charming",
    name: "Eyes of Charming",
    slot: "eyes",
    weightLb: 0,
    costGp: 56000,
    tags: ["charm"],
  }),
  item({
    id: "goggles-of-minute-seeing",
    name: "Goggles of Minute Seeing",
    slot: "eyes",
    weightLb: 0,
    costGp: 2500,
    tags: ["search"],
    automationStatus: "manual",
    automationNotes: "Search bonus not yet modeled.",
  }),
  item({
    id: "goggles-of-night",
    name: "Goggles of Night",
    slot: "eyes",
    weightLb: 0,
    costGp: 12000,
    tags: ["darkvision"],
  }),
  item({
    id: "gem-of-seeing",
    name: "Gem of Seeing",
    slot: "eyes",
    weightLb: 0,
    costGp: 75000,
    tags: ["true-seeing"],
  }),
  item({
    id: "goggles-of-truesight",
    name: "Goggles of Truesight",
    slot: "eyes",
    weightLb: 0,
    costGp: 75000,
    tags: ["true-seeing"],
  }),
  item({
    id: "deathwatch-eyes",
    name: "Deathwatch Eyes",
    slot: "eyes",
    weightLb: 0,
    costGp: 2000,
    tags: ["divination"],
  }),
];
